title: Finance & Tech Insights
description: Crypto, AI, and Stock Market deep dives.
url: "https://blog-finance.enjoy-onepage.com"
baseurl: ''
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
