title: Finance & Tech Insights
description: Crypto, AI, and Stock Market deep dives.
url: 'https://somsoo.github.io/economy-blog'
baseurl: ''
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
